### ISSUE TITLE
Syntax error in fetch() of AuthService

### ISSUE THREAD

**Issue by JLWJL** [pantharshit00/jwt-react-auth#1]
This block got a syntax error of `Unexpected token` at `...options`. 
```
 return fetch(url, {
            headers,
            ...options
})
```
I found out from some search that `{obj1, ...objx}` is called 'spread syntax' and it needs a configuration in `.babel.rc` file like this 
```
{
  "plugins": ["transform-object-rest-spread"]
}
```
However, I did not find the regarding configuration in your repo, I wonder how you made it work?

**Comment by pantharshit00** [comment]
Which version of node you are using? I am using node 8.7 which I guess supports spread natively.
