### ISSUE TITLE
Syntax error with fetch ...options

### ISSUE THREAD

**Issue by aleksandarbatin** [pantharshit00/jwt-react-auth#2]
Please can you halp me solve the problem. I tried to implement authentication on my project but I didnt set webpack with create-react-app and react-scripts so. My webpack couldnt recognize this syntax: 
```
return fetch(url, {
            headers,
            ...options
        })
```
it throw me a syntax erros and culdnt finish login proces. Is there some other way to write this? @ @pantharshit00

**Comment by pantharshit00** [comment]
It might be something with your node version as it might not be recognising spread syntax.

Try to update your node version. 
If problem persists send a screenshot of your text editor.
